export const CALC_MANDLEBROT_BLOCK = 'CALC_MANDLEBROT_BLOCK';
export const CALC_MANDLEBROT_BLOCK_SMOOTH = 'CALC_MANDLEBROT_BLOCK_SMOOTH';
export const CALC_BURNING_SHIP_BLOCK = 'CALC_BURNING_SHIP_BLOCK';
export const CALC_BURNING_SHIP_BLOCK_SMOOTH = 'CALC_BURNING_SHIP_BLOCK_SMOOTH';
export const CALC_MULTIBROT_BLOCK = 'CALC_MULTIBROT_BLOCK';
export const CALC_MULTIBROT_BLOCK_SMOOTH = 'CALC_MULTIBROT_BLOCK_SMOOTH';
export const CALC_TRICORN_BLOCK = 'CALC_TRICORN_BLOCK';
export const CALC_TRICORN_BLOCK_SMOOTH = 'CALC_TRICORN_BLOCK_SMOOTH';
